# 使用官方的 Node.js 映像作為基礎映像
FROM node:16

# 在容器內建立應用程式的工作目錄
WORKDIR /usr/src/app

# 將 package.json 與 package-lock.json 複製到工作目錄中
COPY package*.json ./

# 安裝相依套件
RUN npm install

# 將整個應用程式複製到容器內的工作目錄中
COPY . .

# 暴露應用程式執行的端口
EXPOSE 3000

# 定義容器啟動時要執行的命令
CMD [ "node", "app.js" ]