version: '3.4'

services:
  twitter:
    build:
      context: .
      dockerfile: dockerFile
    container_name: twitter
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"  
    depends_on:
      - twitterdb
    networks:
      - twitterNet
  
  twitterdb:
    image: mysql:8.0
    container_name: twitterdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DB=ac_twitter_workspace
    expose:
      - 3308
    ports:
      - 3308:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - twitterNet

networks:
  twitterNet:
    driver: bridge
  
